### PR TITLE
Smorci Day 02

### PR DESCRIPTION
**Pull request by smorci**
I thought of this iterator peek in the future solution. 
This is a draft, will investigate further and maybe think of another solution and compare.
Will provide README and explanations in the future.

### CODE REVIEW

**Comment by smorci** [comment]
I dwelled into iterators at one point and thought I could solve the problem with them, so I did, whilst realizing how bad this looks to someone looking at it for the first time. 

Better, more robust and elegant solutions exist out there, so I will find a new one.

**Comment by brainrake** [comment]
Hey, good progress here. The iterator solution could be more... iterative (iterating over "Nemo" too).
Both solutions print a string instead of returning it as the exercise statement requires, please fix that.
Please split the solution into smaller functions that do one thing (eg. one function for finding nemo's index and one for turning the index into a string. Always try to split your code into a pure (side-effect-free, functional) core made of small functions and an imperative (effectful, modifying the state of the world) shell that interacts with the outside world, and push as much as possible into the pure core. Effects are things you can observe when calling a procedure, other than the return value, and make testing (and thinking about, and composing) procedures hard.

**Comment by smorci** [comment]
@brainrake @botiboti 

Are we okay with having multiple solutions in `lib.rs` and flagging them with docstrings based on their performance (bad, better, best or something) and providing examples with them?

Maybe provide binary examples for all of them and one in the main binary crate that we deem best?

Of course just one solution is also fine.

Note: I am bringing this up because I imagine IRL when you maintain a library a problem could have a solution implemented that is updated or rewritten at one point, thus the old one gets deprecated. And the deprecation process is a practice in itself.

**Comment by brainrake** [comment]
Having multiple versions sould be fine, however, not sure how this impacts testing. How can we run the same tests on different functions?
Sometimes we have multiple types implementing an interface, like Vec and LinkedList have IntoIterator. Those are usually in separate modules.
Maybe having them in separate modules is the way to go.

**Comment by botiboti** [comment]
image

**Pull request closed without merging**
